* 介绍
GNU Radio 是一个开源的软件定义无线电（SDR）平台。它有一个世界范围内的开发者和用户社区为其贡献了坚实的基础代码，并提供了许多软件和硬件的实际应用。它提供了一个完整的开发环境，以创建您自己的无线电，为您处理所有的硬件接口、多线程、可移植性的问题。GNU Radio 提供所有通用软件无线电需要的库，包括各种调制方式（GMSK、PSK、QAM、OFDM 等）、纠错码（R‐S 码、维特比码、Turbo 码）、信号处理模块（最优滤波器、FFT、均衡器、定时恢复）和调度。它是一个很灵活的系统，允许用户使用C++或者Python 开发应用程序。

GNU Radio是一个设计框架，用户可以用来设计、模拟和部署的真实高效无线电系统。这是一个高度模块化，自带flowgraph流程图，集成处理各种信号的库，可以很方便的将各个模块结合到一起来处理复杂的信号。 GNU Radio已经被广泛应用于无线电世界，可以用电脑软件处理包括音频处理、移动通信、卫星跟踪、雷达系统、GSM网络、数字信号广播等等。
GNU Radio 硬件平台本身并不是非常特殊的硬件，也没有包含现成的通信协议和通信标准，比如802.11、Zigbee、LTE等，但它可以用于开发并实现任何频率、任何协议的无线电通信。

0x120 为什们要用GNU Radio？
曾经无线电通信方面的开发，工程师需要设计用于检测特定信号的特定设备，设计专用IC用来解码或者编码特定信号，才能进行数据通信和传输，整个调试过程成本很高而且很费时间。 Software-Defined Radio 软件无线电SDR使得开发变得非常简单，只要有钱买一块SDR板子并且有能力使用它，就可以用算法在计算机的软件上处理无线电信号。
当你的电脑连接了软件无线电设备，编写一个程序，用于串联各个算法和数据，每次都从头开始写你会觉得非常麻烦：为什么每次都要重新实现一个标准的过滤器？为什么要关注数据在不同处理模块之间的通信？为什么不能用高度集成的模块进行实现，非得自己写？而且怎么才能让程序能更好的兼容各种平台，比如一个功率只有几W的嵌入式设备？
在GNU Radio中，这是一个集成度非常好的信号处理模块框架，这里面封装了非常多的可以重复使用的模块，而且扩展性非常出色，提供了标准算法的扩展库，并且在各种平台上都有很大程度的优化，它还有很多很多例子让你可以很轻松的上手。


GNU Radio 是免费的软件开发工具套件。它提供信号运行和处理模块，用它可以在易制作的低成本的射频（RF）硬件和通用微处理器上实现软件定义无线电。这套套件广泛用于业余爱好者，学术机构和商业机构用来研究和构建无线通信系统。 GNU Radio 的应用主要是用 Python 编程语言来编写的。但是其核心信号处理模块是C++在带浮点运算的微处理器上构建的。因此，开发者能够简单快速的构建一个实时、高容量的无线通信系统。 尽管其主要功用不是用来做仿真器，GNU Radio 在没有射频 RF 硬件部件的境况下还可用作对预先存储或（信号发生器）生成的数据进行信号处理的算法研究的平台。

GNU Radio 遵从 GNU GPL V3.0. 所有其代码归 FSF - Free Software Foundation （自由软件基金）所有。

GNU Radio 
开源软件无线电（Gnuradio）或 开源软件定义无线电 是一个对学习，构建和部署软件定义无线电系统的免费软件工具包。发起于2001年，Gnuradio1 现在成为 GNU 的正式项目之一。慈善家 John Gilmore 发起并捐助 $320,000.00 (US) 给 Eric Blossom 用来构建代码和维护。

简介
Gnuradio [1]  是一个无线电信号处理方案，它遵循 GNU 的 GPL [2]  的条款分发。它的目的是给普通的软件编制者提供探索电磁波的机会，并激发他们聪明的利用射频电波的能力。
正如所有软件定义无线电系统的定义， 可重构性是其最重要的功能。再也不需购买一大堆发射接收设备，只要一台可以装载信号处理软件（这里：Gnuradio [1]  ）通用的设备。目前它虽然只定义几个有限的无线电功能，但是只要理解无线发射系统的机理（算法），你便可以任意的配置去接受它。
Gnuradio [1]  起源于美国的麻省理工学院的 SpectrumWare 项目小组开发的 Pspectra 代码的分支。2004年被完全重写。所以今天的 Gnuradio 已不包含原 Pspectra 任何代码。另外值得一提的是 Pspectra 已被用作创立商业化的 Vanu Software Radio.
Gnuradio [1]  开发了通用软件无线电外设（USRP [3]  和USRP2 [4]  )，它是一个包含4个64 MS/s 的12位 ADC，4 个 128 MS/s 的 14 位的 DAC，以及其它支持线路包括高速的 USB 2.0 接口。该USRP能够处理的信号频率高达16 MHz宽。一些发射器和接收器的插件子板，可覆盖0至5.9MHz 频段。 它是Ettus [5]  研发的。

意义
开源软件无线电 GNU Radio [1]  是免费的软件开发工具套件。它提供信号运行和处理模块，用它可以在易制作的低成本的射频（RF）硬件和通用微处理器上实现软件定义无线电。这套套件广泛用于业余爱好者，学术机构和商业机构用来研究和构建无线通信系统。
GNU Radio [1]  的应用主要是用 Python 编程语言来编写的。但是其核心信号处理模块是C++在带浮点运算的微处理器上构建的。因此，开发者能够简单快速的构建一个实时、高容量的无线通信系统。
尽管其主要功用不是仿真器，GNU Radio [1]  在没有射频 RF 硬件部件的境况下支持对预先存储和（信号发生器）生成的数据进行信号处理的算法的研究。

Ettus Research，公司是世界领先的低成本的软件无线电平台供应商。
Ettus Research公司是世界领先的低成本的软件无线电平台供应商，其中包括广受欢迎的通用软件无线电外设（USRP）系列产品，USRP的与整体系统的较低的系统价格，非常好的硬件和软件的可用性，被世界上成千上万的工程师使用着，并且是在软件定义无线电（SDR）的硬件算法的开发，研究和的原型设计的首选。
USRP的产品系列是为DC到6GHz的射频应用而设计的，包括多天线（MIMO）系统。应用领域包括-空白电视信号频段，移动电话，公众安全，频谱监测，无线电网络，认知无线电，卫星导航和业余无线电爱好者 [1]  。・

* 安装

** pybombs
安装前确保电脑中存在 doxygen xmlto sphinx,  这些是生成文档的必备工具。

使用 pybombs 安装可以省去很多麻烦
使用 [[https://www.gnuradio.org/blog/pybombs-the-what-the-how-and-the-why/][pip 安装]] pybombs

#+BEGIN_SRC sh
pybombs rebuild gnuradio #不再下载，节省时间
pybombs update gnuradio #更新
#+END_SRC

** 生成学习文档
   - sphinx
     通过运行 GNU radio 源代码 build 目录下的 run_sphinx_build.sh, 可以生成文档：
   - doxygen



* 开源软件无线电介绍
** 什么是GNU Radio(开源软件无线电)
软件无线电－>
** 人们用GNU Radio 做什么
** GNU Radio 软件架构
** GNU Radio 硬件平台
** 研究领域快速验证的例子
*** gr-
*** gr-radar
** 实例演示
*** 搭建 FM 接收站
** 总结
