* 电子战基本概念
  EW 包括 ES, EA, EP, 在较早时候，这三者分别称为 ESM, ECM, ECCM。其中，早期的 ECM 中并不包括 ARM、高能微波、高能激光，现在都含在EA中。

  在某些场合 ESM, ECM, ECCM 这三种称法还在使用中。
| EW   | 电子战                                   | Electronic warfare                 |
| ES   | 电子战支援                               | Electronic warfare support         |
| EA   | 电子攻击                                 | Electronic attack                  |
| EP   | 电子防护                                 | Electronic protection              |
| ESM  | 电子战支援手段（电子侦察），ES过去的叫法 | Electronic support measures        |
| ECM  | 电子对抗手段（电子干扰）                 | Electronic Countermeasures         |
| ECCM | 电子反干扰                               | Electronic Counter-Countermeasures |
|      |                                          |                                    |
** ES
 ES 通常需要高精度的输出，典型的例子是海军的电子战系统就将ES的输出用于武器的目标指示。

 ES 和 SIGINT(signal intelligence 信号智能) 比较相似。

 SIGINT是一个通用的术语，它包括无线电频段系统(通信智能或COMINT)、雷达频段系统(电子智能或ELINT)

*** 电子智能
 用于确定敌方的能力。需要测量详细的参数。

 ES 和 ELINT 的区别：
 ES 为战术运用，因此实时性要求较高。通过收集和分析众多的雷达信号确定具有威胁的雷达、对雷达定位、确定雷达的工作模式。
 在收到信号几秒钟内就要给出分析结果。信号采集的颗粒度之以完成目的为准则，面向行动。

|              | ES                                           | ELINT                                                |
|--------------+----------------------------------------------+------------------------------------------------------|
| 使命任务     | 识别、定位威胁，实现平台的自卫               | 分析信号的细节特征                                   |
| 接收信号类型 | 接收直射信号                                 | 类似于窃听者接收作用在别人之间的信号                 |
| 时效性       | 实时性要求高                                 | 非实时分析                                           |
| 设备性能要求 | 小天线、低增益、低灵敏度，空域宽开、时域宽开 | 大天线、高增益、高灵敏度，可能时极窄波束、极窄带宽的 |


ES 实时分析：从目标识别到自卫响应的时间只在分钟量级甚至秒量级。
ELINT 非实时分析的例子：侦察卫星通过长达6个月的信号收集，分析后发现一段未收到过的长度仅位几秒钟的雷达信号，虽然实时性不高，但确是非常有用的。

*** 态势感知
Situational Awareness(SA). 态势感知是一个广泛使用的术语，在不同的领域，态势感知具有不同的含义。
对于移动平台（如飞机、轮船和坦克等）而言，SA提供友方和敌方相对于平台的战术部署信息。在现代系统中，这些信息来自于平台的光学和电子传感器，以及平台之外的其他资源。机动平台利用这些信息来优化其移动路线、武器管理以及自卫策略。

*** 雷达告警
    雷达告警包含如下任务：实现对敌方雷达的检测、识别、定位。虽然只有敌方的攻击武器才是真正的威胁，但武器相关联的信号通常都被称为威胁：
    红色威胁对应敌方与武器相关的信号；蓝色威胁是类似的友方信号；灰色威胁是与敌方信号相像的自然界信号。

    ES的任务之一就是正确地识别这些信号的类型，排出蓝色和灰色威胁。蓝色威胁和灰色威胁的存在增加了识别敌方信号的复杂性，一方面是需要分析的信号量增大了，另一方面是为了区分出不同的信号，需要分析更多细微的差别。

*** 雷达告警接收机
    RWRs 截获和分析敌方雷达的辐射信号，进而确定敌方雷达所控制的武器类型和位置。RWR 将截获信号与一个存有敌方全部（或许多）类型雷达的信号参数表相比较，从而确定当前的信号中存在哪些雷达，它们的工作模式以及相对于平台的位置。
    并将这些信息实时地显示给机组人员、船员等，并引导 EA 设备做出适当的响应。

*** 辐射源个体识别
    Specific Emitter Identification (SEI). SEI 不仅确定所截获信号的辐射源类型，而且还确定敌方目标平台。
    它基于一个已知辐射源的参数表。

*** 雷达检测距离 vs 目标截获距离
    ES 的雷达信号截获距离取决于雷达参数、ES系统的灵敏度、天线增益。
    雷达的作用距离取决于雷达的距离方程。

    低截获雷达可以在被对方的 ES 系统截获前就发现对方。

** EA
电子攻击包含使用电子技术降低敌方军事行动有效性的所有手段。直接与敌方的雷达和通信设备相对抗。包括：干扰、箔条、红外、反辐射武器、高能辐射武器等。

** EP

